pipeline {
    agent any 
    stages {
        stage('Install NPM modules') {
            steps {
                sh '''
                    npm install 
                '''
            }
        }
        stage('Lint') {
            steps {
                sh '''
                    npm run lint
                '''
            }
        }
        stage ('Build') {
            steps {
                sh '''
                    npm run build
                '''
            }
        }
        stage ('Tests') {
            steps {
                sh '''
                    npm run test:unit -- -R xunit | grep "^<"  > tests_result.xml
                '''
            }
        }
        stage ('Archive & Publish build') {
            steps {
                sh '''
                    tar -C dist -czvf drummer.tar.gz .
                '''
                archiveArtifacts artifacts: 'drummer.tar.gz', fingerprint: true, onlyIfSuccessful: true
                xunit([JUnit(deleteOutputFiles: true, failIfNotNew: true, pattern: 'tests_result.xml', skipNoTestFiles: false, stopProcessingIfError: true)])
            }
        }
    }
}