pipeline {
    agent any 
    stages {
        stage('Install NPM modules') {
            steps {
                sh '''
                    npm install 
                '''
            }
        }
        stage('Lint') {
            steps {
                sh '''
                    npm run lint
                '''
            }
        }
        stage ('Build') {
            steps {
                sh '''
                    npm run build
                '''
            }
        }
    }
}