pipeline {
    agent any 
    stages {
        stage('Install NPM modules') {
            steps {
                npm install 
            }
        }
        stage('Lint') {
            steps {
                npm run lint
            }
        }
        stage ('Build') {
            steps {
                npm run build
            }
        }
    }
}